Document: ibus-pinyin
Title: Debian ibus-pinyin Manual
Author: <insert document author here>
Abstract: This manual describes what ibus-pinyin is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ibus-pinyin/ibus-pinyin.sgml.gz

Format: postscript
Files: /usr/share/doc/ibus-pinyin/ibus-pinyin.ps.gz

Format: text
Files: /usr/share/doc/ibus-pinyin/ibus-pinyin.text.gz

Format: HTML
Index: /usr/share/doc/ibus-pinyin/html/index.html
Files: /usr/share/doc/ibus-pinyin/html/*.html

  
